/*
** See Copyright Notice In elf.h
** elf-tkn.h (Autogenerated)
** This file was autogenerated by token.elf in tools
*/


#define FIRST_KEYWORD 1
#define  LAST_KEYWORD 28


#define FIRST_MACRO 29
#define  LAST_MACRO 34


typedef struct elToken {
	unsigned char type;
	elFileLine line;
	unsigned int eol: 1;
	union {
		char *s;
		elInteger i;
		elNumber n;
	};
} elToken;


typedef enum elTokenType {
	TK_NONE                 = 0,
	TK_ELF                  = 1,
	TK_LOAD                 = 2,
	TK_USING                = 3,
	TK_TRY                  = 4,
	TK_CATCH                = 5,
	TK_FINALLY              = 6,
	TK_NEW                  = 7,
	TK_THIS                 = 8,
	TK_ENUM                 = 9,
	TK_FUN                  = 10,
	TK_LET                  = 11,
	TK_FOR                  = 12,
	TK_OVER                 = 13,
	TK_IN                   = 14,
	TK_DO                   = 15,
	TK_WHILE                = 16,
	TK_BREAK                = 17,
	TK_CONTINUE             = 18,
	TK_LEAVE                = 19,
	TK_LASTLY               = 20,
	TK_IF                   = 21,
	TK_IFF                  = 22,
	TK_ELIF                 = 23,
	TK_THEN                 = 24,
	TK_ELSE                 = 25,
	TK_NIL                  = 26,
	TK_TRUE                 = 27,
	TK_FALSE                = 28,
	TK_M_LINE_NUMBER        = 29,
	TK_M_LINE_CHAR          = 30,
	TK_M_FILE_NAME          = 31,
	TK_M_REGISTER           = 32,
	TK_M_LEVEL              = 33,
	TK_INTEGER              = 34,
	TK_NUMBER               = 35,
	TK_STRING               = 36,
	TK_LETTER               = 37,
	TK_WORD                 = 38,
	TK_QUESTION_MARK        = 39,
	TK_EXCLAMATION_MARK     = 40,
	TK_NEGATE               = 41,
	TK_NIL_ASSIGN      = 42,
	TK_ASSIGN               = 43,
	TK_COLON                = 44,
	TK_SEMI_COLON           = 45,
	TK_DOT                  = 46,
	TK_COMMA                = 47,
	TK_SQUARE_LEFT          = 48,
	TK_SQUARE_RIGHT         = 49,
	TK_CURLY_LEFT           = 50,
	TK_CURLY_RIGHT          = 51,
	TK_PAREN_LEFT           = 52,
	TK_PAREN_RIGHT          = 53,
	TK_MUL                  = 54,
	TK_DIV                  = 55,
	TK_MODULUS              = 56,
	TK_ADD                  = 57,
	TK_SUB                  = 58,
	TK_RIGHT_SHIFT          = 59,
	TK_LEFT_SHIFT           = 60,
	TK_LESS_THAN            = 61,
	TK_LESS_THAN_EQUAL      = 62,
	TK_GREATER_THAN         = 63,
	TK_GREATER_THAN_EQUAL   = 64,
	TK_EQUALS               = 65,
	TK_NOT_EQUALS           = 66,
	TK_BIT_AND              = 67,
	TK_BIT_OR               = 68,
	TK_BIT_XOR              = 69,
	TK_LOG_AND              = 70,
	TK_LOG_OR               = 71,
	TK_DOT_DOT              = 72,
} elTokenType;


typedef struct ltokenintel {
	char *name;
	char prec;
	elf_hashint hash;
} ltokenintel;


elf_globaldecl ltokenintel elf_tkintel[] = {
	{"none",                 -3, 0},
	{"elf",                  -2, 1485326630},
	{"load",                 -2, 3859241449},
	{"using",                -2, 1775113223},
	{"try",                  -2, 2887626766},
	{"catch",                -2, 1116268876},
	{"finally",              -2, 2618047400},
	{"new",                  -2, 681154065},
	{"this",                 -2, 3660305025},
	{"enum",                 -2, 2171383808},
	{"fun",                  -2, 2832955486},
	{"let",                  -2, 1349190650},
	{"for",                  -2, 2901640080},
	{"over",                 -2, 838226447},
	{"in",                   -2, 1094220446},
	{"do",                   -2, 1646057492},
	{"while",                -2, 231090382},
	{"break",                -2, 3378807160},
	{"continue",             -2, 2977070660},
	{"leave",                -2, 1416872128},
	{"lastly",               -2, 3467888482},
	{"if",                   -2, 959999494},
	{"iff",                  -2, 1943388448},
	{"elif",                 -2, 3232090307},
	{"then",                 -2, 3844270454},
	{"else",                 -2, 3183434736},
	{"nil",                  -2, 228849900},
	{"true",                 -2, 1303515621},
	{"false",                -2, 184981848},
	{"line_number",          -1, 3505311321},
	{"line_char",            -1, 704563284},
	{"file_name",            -1, 3894850831},
	{"register",             -1, 761819584},
	{"level",                -1, 2610554845},
	{"literal-integer",      -3, 0},
	{"literal-number",       -3, 0},
	{"literal-string",       -3, 0},
	{"literal-letter",       -3, 0},
	{"identifier",           -3, 0},
	{"?",                    -3, 0},
	{"!",                    -3, 0},
	{"!",                    -3, 0},
	{"?=",                   -3, 0},
	{"=",                    -3, 0},
	{":",                    -3, 0},
	{";",                    -3, 0},
	{".",                    -3, 0},
	{",",                    -3, 0},
	{"[",                    -3, 0},
	{"]",                    -3, 0},
	{"{",                    -3, 0},
	{"}",                    -3, 0},
	{"(",                    -3, 0},
	{")",                    -3, 0},
	{"*",                    11, 0},
	{"/",                    11, 0},
	{"%",                    11, 0},
	{"+",                    10, 0},
	{"-",                    10, 0},
	{">>",                   9, 0},
	{"<<",                   9, 0},
	{"<",                    8, 0},
	{"<=",                   8, 0},
	{">",                    8, 0},
	{">=",                   8, 0},
	{"==",                   7, 0},
	{"!=",                   7, 0},
	{"&",                    6, 0},
	{"|",                    5, 0},
	{"^",                    4, 0},
	{"&&",                   3, 0},
	{"||",                   2, 0},
	{"..",                   1, 0},
};


