/*
** See Copyright Notice In elf.h
** elf-tkn.h (Autogenerated)
** This file was autogenerated by token.elf in tools
*/


#define FIRST_KEYWORD 1
#define  LAST_KEYWORD 28


typedef struct elToken {
	unsigned char type;
	elf_lineid line;
	unsigned int eol: 1;
	union {
		char *s;
		elInteger i;
		elNumber n;
	};
} elToken;


typedef enum ltokentype {
	TK_NONE                 = 0,
	TK_ELF                  = 1,
	TK_LOAD                 = 2,
	TK_USING                = 3,
	TK_TRY                  = 4,
	TK_CATCH                = 5,
	TK_FINALLY              = 6,
	TK_NEW                  = 7,
	TK_THIS                 = 8,
	TK_ENUM                 = 9,
	TK_FUN                  = 10,
	TK_LET                  = 11,
	TK_FOR                  = 12,
	TK_FOREACH              = 13,
	TK_IN                   = 14,
	TK_DO                   = 15,
	TK_WHILE                = 16,
	TK_BREAK                = 17,
	TK_CONTINUE             = 18,
	TK_LEAVE                = 19,
	TK_LASTLY               = 20,
	TK_IF                   = 21,
	TK_IFF                  = 22,
	TK_ELIF                 = 23,
	TK_THEN                 = 24,
	TK_ELSE                 = 25,
	TK_NIL                  = 26,
	TK_TRUE                 = 27,
	TK_FALSE                = 28,
	TK_INTEGER              = 29,
	TK_NUMBER               = 30,
	TK_STRING               = 31,
	TK_LETTER               = 32,
	TK_WORD                 = 33,
	TK_QUESTION_MARK        = 34,
	TK_EXCLAMATION_MARK     = 35,
	TK_NEGATE               = 36,
	TK_ASSIGN_QUESTION      = 37,
	TK_ASSIGN               = 38,
	TK_COLON                = 39,
	TK_SEMI_COLON           = 40,
	TK_DOT                  = 41,
	TK_COMMA                = 42,
	TK_SQUARE_LEFT          = 43,
	TK_SQUARE_RIGHT         = 44,
	TK_CURLY_LEFT           = 45,
	TK_CURLY_RIGHT          = 46,
	TK_PAREN_LEFT           = 47,
	TK_PAREN_RIGHT          = 48,
	TK_MUL                  = 49,
	TK_DIV                  = 50,
	TK_MODULUS              = 51,
	TK_ADD                  = 52,
	TK_SUB                  = 53,
	TK_RIGHT_SHIFT          = 54,
	TK_LEFT_SHIFT           = 55,
	TK_LESS_THAN            = 56,
	TK_LESS_THAN_EQUAL      = 57,
	TK_GREATER_THAN         = 58,
	TK_GREATER_THAN_EQUAL   = 59,
	TK_EQUALS               = 60,
	TK_NOT_EQUALS           = 61,
	TK_BIT_AND              = 62,
	TK_BIT_OR               = 63,
	TK_BIT_XOR              = 64,
	TK_LOG_AND              = 65,
	TK_LOG_OR               = 66,
	TK_DOT_DOT              = 67,
} ltokentype;


typedef struct ltokenintel {
	char *name;
	char prec;
	elf_hashint hash;
} ltokenintel;


elf_globaldecl ltokenintel elf_tkintel[] = {
	{"none",                 -2, 0},
	{"elf",                  -1, 1485326630},
	{"load",                 -1, 3859241449},
	{"using",                -1, 1775113223},
	{"try",                  -1, 2887626766},
	{"catch",                -1, 1116268876},
	{"finally",              -1, 2618047400},
	{"new",                  -1, 681154065},
	{"this",                 -1, 3660305025},
	{"enum",                 -1, 2171383808},
	{"fun",                  -1, 2832955486},
	{"let",                  -1, 1349190650},
	{"for",                  -1, 2901640080},
	{"foreach",              -1, 3076491097},
	{"in",                   -1, 1094220446},
	{"do",                   -1, 1646057492},
	{"while",                -1, 231090382},
	{"break",                -1, 3378807160},
	{"continue",             -1, 2977070660},
	{"leave",                -1, 1416872128},
	{"lastly",               -1, 3467888482},
	{"if",                   -1, 959999494},
	{"iff",                  -1, 1943388448},
	{"elif",                 -1, 3232090307},
	{"then",                 -1, 3844270454},
	{"else",                 -1, 3183434736},
	{"nil",                  -1, 228849900},
	{"true",                 -1, 1303515621},
	{"false",                -1, 184981848},
	{"literal-integer",      -2, 0},
	{"literal-number",       -2, 0},
	{"literal-string",       -2, 0},
	{"literal-letter",       -2, 0},
	{"identifier",           -2, 0},
	{"?",                    -2, 0},
	{"!",                    -2, 0},
	{"!",                    -2, 0},
	{"?=",                   -2, 0},
	{"=",                    -2, 0},
	{":",                    -2, 0},
	{";",                    -2, 0},
	{".",                    -2, 0},
	{",",                    -2, 0},
	{"[",                    -2, 0},
	{"]",                    -2, 0},
	{"{",                    -2, 0},
	{"}",                    -2, 0},
	{"(",                    -2, 0},
	{")",                    -2, 0},
	{"*",                    11, 0},
	{"/",                    11, 0},
	{"%",                    11, 0},
	{"+",                    10, 0},
	{"-",                    10, 0},
	{">>",                   9, 0},
	{"<<",                   9, 0},
	{"<",                    8, 0},
	{"<=",                   8, 0},
	{">",                    8, 0},
	{">=",                   8, 0},
	{"==",                   7, 0},
	{"!=",                   7, 0},
	{"&",                    6, 0},
	{"|",                    5, 0},
	{"^",                    4, 0},
	{"&&",                   3, 0},
	{"||",                   2, 0},
	{"..",                   1, 0},
};


