/*
** See Copyright Notice In elf.h
** elf-gen.h
** Bytecode Generator (node -> bytecode)
*/


#define NO_SLOT (-1)
#define NO_BYTE (-1)
#define NO_JUMP (-0)
#define NO_LINE (-0)


#define BLOCK_LOOP 0x01

/* added when a break, leave or continue
statement is found */
#define BLOCK_ENDED  0x02

/* added when a piece of block is delayed */
#define BLOCK_DELAYED 0x04


typedef struct elf_fileloop {
	elf_byteid  entry;
	elf_byteid *falsejumps;
	elf_byteid *truejumps;
	/* the node and register associated
	with the loop increment */
	elf_nodeid  x;
	elf_localid r;
} elf_fileloop;


typedef struct elf_fileblock elf_fileblock;
typedef struct elf_fileblock {
	elf_fileblock *enclosing;
	elBool flags;
	int level;
	int xmemory;
	int xentity;
	elf_byteid entry;
	elf_byteid jumpover;
	elf_byteid *leavejumps;
	elf_fileloop loop;
} elf_fileblock;


/* Contains list of false and true jumps
generated by some boolean expression. */
typedef struct ljlist {
	elf_byteid *t,*f;
} ljlist;


/* Contains list of jumps generated
by a select statement, such as if else */
typedef struct Select {
	/* Conditional false jump instructions
	to be patched so that they jump to
	the next block or instruction */
	elf_byteid *jz;

	/* list of exit jump instructions from
	each block to be patched */
	elf_byteid *j;
} Select;


void langL_moveto(elFileState *fs, elf_lineid line, elf_nodeid x, elf_nodeid y);
void langL_localload(elFileState *fs, elf_lineid line, elBool reload, elf_localid x, elf_localid y, elf_nodeid id);
elf_localid elf_genlocalize(elFileState *fs, elf_lineid line, elf_nodeid id);


void elf_enterlastlyblock(elFileState *fs, elf_lineid line, elf_fileblock *bl);
void elf_closelastlyblock(elFileState *fs, elf_lineid line, elf_fileblock *bl);


elf_byteid langL_branchiffalse(elFileState *fs, ljlist *js, elf_localid x, elf_nodeid id);
elf_byteid langL_branchiftrue(elFileState *fs, ljlist *js, elf_localid x, elf_nodeid id);
elf_byteid *langL_jumpiftrue(elFileState *fs, ljlist *js, elf_localid x, elf_nodeid id);
elf_byteid *langL_jumpiffalse(elFileState *fs, ljlist *js, elf_localid x, elf_nodeid id);


enum {
	L_IF  = 0, // JZ
	L_IFF = 1, // JNZ
};


void elf_genbeginif(elFileState *fs, elf_lineid line, Select *s, elf_nodeid x, int z);
void langL_addelif(elFileState *fs, elf_lineid line, Select *s, elf_nodeid x);
void langL_addelse(elFileState *fs, elf_lineid line, Select *s);
void langL_addthen(elFileState *fs, elf_lineid line, Select *s);
void langL_closeif(elFileState *fs, elf_lineid line, Select *s);


void elf_beginrangedloop(elFileState *fs, elf_lineid line, elf_nodeid x, elf_nodeid lo, elf_nodeid hi);
void elf_closerangedloop(elFileState *fs, elf_lineid line);

void langL_begindowhile(elFileState *fs, elf_lineid line);
void langL_closedowhile(elFileState *fs, elf_lineid line, elf_nodeid x);

void langL_beginwhile(elFileState *fs, elf_lineid line, elf_nodeid x);
void langL_closewhile(elFileState *fs, elf_lineid line);


void elf_enterblock(elFileState *fs, elf_fileblock *bl, elBool flags);
void elf_leaveblock(elFileState *fs);
