/*
** See Copyright Notice In elf.h
** elf-file.h
** Loading Structures
*/


/* Entity: high-level data structure used for
lexical scoping, binds a name to some
value or compile time thing. */

#define NO_ENTITY -1

typedef int elEntityId;
typedef int elBlockId;

typedef struct {
	elEntityId id;
} elEntityIdTypeGuard;


typedef struct elFileEntity {
	char *name;
	elf_lineid line;
	elNodeId node;
	elRegId slot;
	int level;
	elBool flags;
} elFileEntity;


#define LOAD_RELOAD 		0x1
#define LOAD_KEEPALIVE	0x2
#define LOAD_ALLOCATE 	0x4

#define NO_SLOT (-1)
#define NO_BYTE (-1)
#define NO_JUMP (-0)
#define NO_LINE (-0)


typedef struct elFileLoopState {
	elByteId entry;
	union { elNodeId index_node, x; };
	elRegId index_register;
	elByteId *false_jumps,*true_jumps;
} elFileLoopState;


#define BLOCK_LOOP 		0x01
#define BLOCK_ENDED  	0x02
#define BLOCK_DELAYED 	0x04


typedef struct elFileBlock elFileBlock;
typedef struct elFileBlock {
	elBool flags;
	// elFileBlock *enclosing;
	// int level;
	int xmemory;
	int xentity;
	int xnode;
	elByteId entry;
	elByteId jumpover;
	elByteId *leavejumps;
	elFileLoopState loop;
} elFileBlock;


/* Contains list of false and true jumps
generated by some boolean expression. */
typedef struct elFileJumplist {
	elByteId *t,*f;
} elFileJumplist;


/* Contains list of jumps generated
by a select statement, such as if else */
typedef struct elSelectState {
	/* Conditional false jump instructions
	to be patched so that they jump to
	the next block or instruction */
	elByteId *jz;
	/* list of exit jump instructions from
	each consecutive block to be patched */
	elByteId *j;
} elSelectState;


typedef struct elMemorySlot elMemorySlot;
typedef struct elMemorySlot {
	elNodeId node;
	elRegId reg;
} elMemorySlot;


typedef struct elMemoryRegion elMemoryRegion;
typedef struct elMemoryRegion {
	elMemorySlot *registry;
	int length;
} elMemoryRegion;


typedef struct elFileFnState elFileFnState;
typedef struct elFileFnState {
	elFileFnState *enclosing;
	elf_lineid line;
	/* maximum number of local register used concurrently
	at any point for this function */
	elRegId nlocals;
	elRegId xmemory;
	/* array of entities from enclosing function,
	use for closure values... */
	elEntityId *enclosure;
	/* this is needed to emit instructions
	relative to the current function we're
	loading, there's always an active function,
	even at file level */
	/* index to first entity within entity list in file. */
	elEntityId entities;
	elBlockId entry_block;
	// elBlockId block;
	elByteId bytes;
	int nloops;
	int nyield;
	/* todo: deprecated */
	/* list of yield jumps to be patched */
	elByteId *yj;
} elFileFnState;


typedef struct elFileState {
	union { elModule *M,*md; };
	union { elState *R,*rt; };
	int file_id;
	char *filename;
	char *linechar;
	char *contents;
	char *thischar;
	int linenumber;
	union {
		struct {
			elToken lasttk,tk,thentk;
		};
		struct {
			elToken last_token,this_token,then_token;
		};
	};
	/* buffer for nodes */
	elNode *nodes;
	elNodeId nnodes;
	/* associates a node to a register
	with the currently active memory
	region, causes nodes with divergent
	evaluation paths to merge and thus
	only be evaluated only once. */
	elMemorySlot memory_region_registry[0x100];
	int memory_region_level;
	/* the current memory region  */
	elMemoryRegion memory_region;
	/* hierarchical list of entities */
	elFileEntity *entities;
	int nentities;

	elFileBlock *blocks;
	union { elBlockId nblocks, level; };

	elFileBlock entry;
	/* hierarchical list of loading functions,
	each allocated in C stack by caller function */
	elFileFnState *fn;
	elByteId bytes;
	int flags;
	elBool debuggerflag;
} elFileState;


elNodeId elf_fs_load_expr(elFileState *fs);
elNodeId elf_load_unary_expr(elFileState *fs, elBool allow_postfix);
void elf_fs_load_stat(elFileState *fs);



void elf_emit_load_to_target(elFileState *fs, elf_lineid line, elNodeId x, elNodeId y);
elRegId elf_emitter_local_load(elFileState *fs, elf_lineid line, elBool reload, elRegId x, elRegId y, elNodeId id);
elRegId elf_emitter_localize(elFileState *fs, elf_lineid line, elNodeId id);
elRegId elf_emitter_relocalize(elFileState *fs, elf_lineid line, elRegId target_register, elNodeIdTypeGuard id);


void elf_emitter_enter_delayed_block(elFileState *fs, elf_lineid line);
void elf_emitter_leave_delayed_block(elFileState *fs, elf_lineid line);


elByteId elf_branch_if_false(elFileState *fs, elFileJumplist *js, elRegId x, elNodeId id);
elByteId elf_branch_if_true(elFileState *fs, elFileJumplist *js, elRegId x, elNodeId id);
elByteId *elf_emit_jump_if_true(elFileState *fs, elFileJumplist *js, elRegId x, elNodeId id);
elByteId *elf_emit_jump_if_false(elFileState *fs, elFileJumplist *js, elRegId x, elNodeId id);


enum {
	L_IF  = 0, // JZ
	L_IFF = 1, // JNZ
};


void elf_emitter_begin_if(elFileState *fs, elf_lineid line, elSelectState *s, elNodeId x, int z);
void elf_emitter_add_elif_clause(elFileState *fs, elf_lineid line, elSelectState *s, elNodeId x);
void elf_emitter_add_else_clause(elFileState *fs, elf_lineid line, elSelectState *s);
void elf_emitter_add_then_clause(elFileState *fs, elf_lineid line, elSelectState *s);
void elf_emitter_add_if_clause(elFileState *fs, elf_lineid line, elSelectState *s);


void elf_emitter_begin_ranged_loop(elFileState *fs, elf_lineid line, elNodeId x, elNodeId lo, elNodeId hi);
void elf_emitter_close_ranged_loop(elFileState *fs, elf_lineid line);

void elf_emitter_begin_do_while_loop(elFileState *fs, elf_lineid line);
void elf_emitter_close_do_while_loop(elFileState *fs, elf_lineid line, elNodeId x);

void elf_emitter_begin_while_loop(elFileState *fs, elf_lineid line, elNodeId x);
void elf_emitter_close_while_loop(elFileState *fs, elf_lineid line);


elBlockId elf_emitter_enter_block(elFileState *fs, elBool flags);
void elf_emitter_leave_block(elFileState *fs);

