/*
** See Copyright Notice In elf.h
** elf-file.h
** Loading Structures
*/


/* Entity: high-level data structure used for
lexical scoping, binds a name to some
value. */

#define NO_ENTITY (elEntityIdTypeGuard){-1}

typedef int elEntityId;

typedef struct {
	elEntityId x;
} elEntityIdTypeGuard;


typedef struct elFileEntity {
	char *name;
	elf_lineid  line;
	elRegId slot;
	elBool enm;
	/* the level in which this name was
	declared, for scoping */
	int level;
	/* todo: we could just put the node here */
} elFileEntity;


#define LOAD_RELOAD 		0x1
#define LOAD_ALLOCATE 	0x4

#define NO_SLOT (-1)
#define NO_BYTE (-1)
#define NO_JUMP (-0)
#define NO_LINE (-0)


typedef struct elFileLoopState {
	elByteId  entry;
	elByteId *falsejumps;
	elByteId *truejumps;
	/* the node and register associated
	with the loop increment */
	elNodeId  x;
	elRegId r;
} elFileLoopState;


#define BLOCK_LOOP 		0x01
#define BLOCK_ENDED  	0x02
#define BLOCK_DELAYED 	0x04


typedef struct elFileBlockState elFileBlockState;
typedef struct elFileBlockState {
	elFileBlockState *enclosing;
	elBool flags;
	int level;
	int xmemory;
	int xentity;
	elByteId entry;
	elByteId jumpover;
	elByteId *leavejumps;
	elFileLoopState loop;
} elFileBlockState;


/* Contains list of false and true jumps
generated by some boolean expression. */
typedef struct elFileJumplist {
	elByteId *t,*f;
} elFileJumplist;


/* Contains list of jumps generated
by a select statement, such as if else */
typedef struct elSelectState {
	/* Conditional false jump instructions
	to be patched so that they jump to
	the next block or instruction */
	elByteId *jz;
	/* list of exit jump instructions from
	each consecutive block to be patched */
	elByteId *j;
} elSelectState;


typedef struct elFileFnState elFileFnState;
typedef struct elFileFnState {
	elFileFnState *enclosing;
	elf_lineid line;
	/* maximum number of local register used concurrently
	at any point for this function */
	elRegId nlocals;
	elRegId xmemory;
	/* array of entities from enclosing function,
	use for closure values */
	elEntityIdTypeGuard *enclosure;
	/* this is needed to emit instructions
	relative to the current function we're
	loading, there's always an active function,
	even at file level */
	/* todo: 'entities' and 'bytes' do we need this now
	that we have blocks ? */
	/* index to first entity within entity list in file. */
	int entities;
	elByteId bytes;
	elFileBlockState entry;
	elFileBlockState *block;
	int nloops;
	int nblocks;
	int nyield;
	/* todo: deprecated */
	/* list of yield jumps to be patched */
	elByteId *yj;
} elFileFnState;


/* Memory Region:
	Memory regions are used to make otherwise
	divergent controls flow paths to converge
	by means of reusing a previously allocated
	registers for a particular node.
*/

typedef struct elMemorySlot elMemorySlot;
typedef struct elMemorySlot {
	elNodeId node;
	elRegId reg;
} elMemorySlot;


typedef struct elMemoryRegion elMemoryRegion;
typedef struct elMemoryRegion {
	elMemorySlot *registry;
	int length;
} elMemoryRegion;


typedef struct elFileState {

	union { elModule *M,*md; };
	union { elState *R,*rt; };
	int file_id;
	char *filename;
	char *linechar;
	char *contents;
	char *thischar;
	int linenumber;
	elToken lasttk,tk,thentk;
	/* buffer for nodes */
	elNode *nodes;
	elNodeId nnodes;
	/* associates a node to a register
	with the currently active memory
	region, causes nodes with divergent
	evaluation paths to merge and thus
	only be evaluated only once. */
	elMemorySlot memory_region_registry[0x100];
	int memory_region_level;
	/* the current memory region  */
	elMemoryRegion memory_region;
	/* the current level, level is incremented
	per level, block or statement or whenever
	it makes sense, represents a visibility
	layer, 0 is for file. */
	int level;
	/* -- hierarchical list of local tags for the current
	- function stack, each function points to a base local
	- tag defined here by index.
	-- remaining locals are file locals, at file level. */
	elFileEntity *entities;
	int nentities;

	elFileBlockState entry;
	/* hierarchical list of loading functions,
	each allocated in C stack by caller function */
	elFileFnState *fn;
	elByteId bytes;
	int flags;
	elBool debuggerflag;
} elFileState;


elNodeId elf_load_file_expr(elFileState *fs);
elNodeId elf_load_unary_expr(elFileState *fs, elBool allow_postfix);
void elf_load_file_stat(elFileState *fs);



void elf_gen_store(elFileState *fs, elf_lineid line, elNodeId x, elNodeId y);
elRegId elf_gen_local_load(elFileState *fs, elf_lineid line, elBool reload, elRegId x, elRegId y, elNodeId id);
elRegId elf_gen_localize(elFileState *fs, elf_lineid line, elNodeId id);
elRegId elf_gen_relocalize(elFileState *fs, elf_lineid line, elRegId target_register, elNodeIdTypeGuard id);


void elf_enter_delayed_block(elFileState *fs, elf_lineid line, elFileBlockState *bl);
void elf_leave_delayed_block(elFileState *fs, elf_lineid line, elFileBlockState *bl);


elByteId elf_branch_if_false(elFileState *fs, elFileJumplist *js, elRegId x, elNodeId id);
elByteId elf_branch_if_true(elFileState *fs, elFileJumplist *js, elRegId x, elNodeId id);
elByteId *elf_emit_jump_if_true(elFileState *fs, elFileJumplist *js, elRegId x, elNodeId id);
elByteId *elf_emit_jump_if_false(elFileState *fs, elFileJumplist *js, elRegId x, elNodeId id);


enum {
	L_IF  = 0, // JZ
	L_IFF = 1, // JNZ
};


void elf_gen_begin_if(elFileState *fs, elf_lineid line, elSelectState *s, elNodeId x, int z);
void elf_gen_add_elif(elFileState *fs, elf_lineid line, elSelectState *s, elNodeId x);
void elf_gen_add_else(elFileState *fs, elf_lineid line, elSelectState *s);
void elf_gen_add_then(elFileState *fs, elf_lineid line, elSelectState *s);
void elf_close_if(elFileState *fs, elf_lineid line, elSelectState *s);


void elf_begin_ranged_loop(elFileState *fs, elf_lineid line, elNodeId x, elNodeId lo, elNodeId hi);
void elf_close_ranged_loop(elFileState *fs, elf_lineid line);

void elf_begin_do_while_loop(elFileState *fs, elf_lineid line);
void elf_close_do_while_loop(elFileState *fs, elf_lineid line, elNodeId x);

void elf_begin_while_loop(elFileState *fs, elf_lineid line, elNodeId x);
void elf_close_while_loop(elFileState *fs, elf_lineid line);


void elf_enter_file_block(elFileState *fs, elFileBlockState *bl, elBool flags);
void elf_leave_file_block(elFileState *fs);

