/*
** See Copyright Notice In elf.h
** (L) lcode.h
** Bytecode Generator (node -> bytecode)
*/


#define NO_SLOT (-1)
#define NO_BYTE (-1)
#define NO_JUMP (-0)
#define NO_LINE (-0)


typedef struct FileBlock {
	elf_byteid j,e;
} FileBlock;


typedef struct elf_fileloop {
	elf_byteid  entry;
	elf_byteid *falsejumps;
	elf_byteid *truejumps;
	/* the node and register associated
	with the loop increment */
	elf_nodeid  x;
	elf_localid r;
} elf_fileloop;


typedef struct elf_fileblock elf_fileblock;
typedef struct elf_fileblock {
	elf_fileblock *enclosing;
	elf_bool flags;
	int level;
	int xmemory;
	int xentity;
	elf_byteid entry;
	elf_byteid *leavejumps;
	elf_fileloop loop;
} elf_fileblock;


/* Contains list of false and true jumps
generated by some boolean expression. */
typedef struct ljlist {
	elf_byteid *t,*f;
} ljlist;


/* Contains list of jumps generated
by a select statement, such as if else */
typedef struct Select {
	/* Conditional false jump instructions
	to be patched so that they jump to
	the next block or instruction */
	elf_byteid *jz;

	/* list of exit jump instructions from
	each block to be patched */
	elf_byteid *j;
} Select;


void langL_moveto(elf_FileState *fs, elf_lineid line, elf_nodeid x, elf_nodeid y);
void langL_localload(elf_FileState *fs, elf_lineid line, elf_bool reload, elf_localid x, elf_localid y, elf_nodeid id);
elf_localid langL_localize(elf_FileState *fs, elf_lineid line, elf_nodeid id);


void langL_begindelayedblock(elf_FileState *fs, elf_lineid line, FileBlock *bl);
void langL_closedelayedblock(elf_FileState *fs, elf_lineid line, FileBlock *bl);


elf_byteid langL_branchiffalse(elf_FileState *fs, ljlist *js, elf_localid x, elf_nodeid id);
elf_byteid langL_branchiftrue(elf_FileState *fs, ljlist *js, elf_localid x, elf_nodeid id);
elf_byteid *langL_jumpiftrue(elf_FileState *fs, ljlist *js, elf_localid x, elf_nodeid id);
elf_byteid *langL_jumpiffalse(elf_FileState *fs, ljlist *js, elf_localid x, elf_nodeid id);


enum {
	L_IF  = 0, // JZ
	L_IFF = 1, // JNZ
};


void langL_beginif(elf_FileState *fs, elf_lineid line, Select *s, elf_nodeid x, int z);
void langL_addelif(elf_FileState *fs, elf_lineid line, Select *s, elf_nodeid x);
void langL_addelse(elf_FileState *fs, elf_lineid line, Select *s);
void langL_addthen(elf_FileState *fs, elf_lineid line, Select *s);
void langL_closeif(elf_FileState *fs, elf_lineid line, Select *s);


void elf_beginrangedloop(elf_FileState *fs, elf_lineid line, elf_nodeid x, elf_nodeid lo, elf_nodeid hi);
void elf_closerangedloop(elf_FileState *fs, elf_lineid line);

void langL_begindowhile(elf_FileState *fs, elf_lineid line);
void langL_closedowhile(elf_FileState *fs, elf_lineid line, elf_nodeid x);

void langL_beginwhile(elf_FileState *fs, elf_lineid line, elf_nodeid x);
void langL_closewhile(elf_FileState *fs, elf_lineid line);


void elf_enterblock(elf_FileState *fs, elf_fileblock *bl, elf_bool flags);
void elf_leaveblock(elf_FileState *fs);
