name: Deploy site

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - "site/**"
      - "build.elf"
      - "project.elf"
      - "bootstrap/windows-x64/**"
      - "dayan-core"
      - ".gitmodules"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Build website
        run: .\bootstrap\windows-x64\manny.exe build.elf site

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/site

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
